import {MigrationInterface, QueryRunner} from "typeorm";

export class Household1623012989593 implements MigrationInterface {
    name = 'Household1623012989593'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_4c5f2c23c34f3921fbad2cd394"`);
        await queryRunner.query(`DROP INDEX "IDX_95bf94c61795df25a515435010"`);
        await queryRunner.query(`CREATE TABLE "temporary_user_groups" ("user_id" integer NOT NULL, "group_id" integer NOT NULL, PRIMARY KEY ("user_id", "group_id"))`);
        await queryRunner.query(`INSERT INTO "temporary_user_groups"("user_id", "group_id") SELECT "user_id", "group_id" FROM "user_groups"`);
        await queryRunner.query(`DROP TABLE "user_groups"`);
        await queryRunner.query(`ALTER TABLE "temporary_user_groups" RENAME TO "user_groups"`);
        await queryRunner.query(`CREATE INDEX "IDX_4c5f2c23c34f3921fbad2cd394" ON "user_groups" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_95bf94c61795df25a515435010" ON "user_groups" ("user_id") `);
        await queryRunner.query(`DROP INDEX "IDX_7514fdc446a1fdcf5b2d39cda6"`);
        await queryRunner.query(`DROP INDEX "IDX_3924be6485a5b5d0d2fe1a94c0"`);
        await queryRunner.query(`CREATE TABLE "temporary_group_permissions" ("group_id" integer NOT NULL, "permission_id" integer NOT NULL, PRIMARY KEY ("group_id", "permission_id"))`);
        await queryRunner.query(`INSERT INTO "temporary_group_permissions"("group_id", "permission_id") SELECT "group_id", "permission_id" FROM "group_permissions"`);
        await queryRunner.query(`DROP TABLE "group_permissions"`);
        await queryRunner.query(`ALTER TABLE "temporary_group_permissions" RENAME TO "group_permissions"`);
        await queryRunner.query(`CREATE INDEX "IDX_7514fdc446a1fdcf5b2d39cda6" ON "group_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3924be6485a5b5d0d2fe1a94c0" ON "group_permissions" ("group_id") `);
        await queryRunner.query(`CREATE TABLE "task_template" ("id" integer PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "description" text, "is_active" boolean, "estimated_time" integer, "reward_points" integer, CONSTRAINT "UQ_b250e915df905dbe641647c8fac" UNIQUE ("id"))`);
        await queryRunner.query(`CREATE TABLE "category" ("id" integer PRIMARY KEY NOT NULL, "date_created" datetime NOT NULL, "description" varchar(255), "name" varchar(255) NOT NULL, CONSTRAINT "UQ_9c4e4a89e3674fc9f382d733f03" UNIQUE ("id"))`);
        await queryRunner.query(`CREATE TABLE "category_task" ("category_id" integer NOT NULL, "task_id" integer NOT NULL, "relevance" integer, "frequency_id" integer, PRIMARY KEY ("category_id", "task_id"))`);
        await queryRunner.query(`CREATE TABLE "frequency" ("id" integer PRIMARY KEY NOT NULL, "name" varchar(20) NOT NULL, "days_apart" integer NOT NULL, CONSTRAINT "UQ_3c0ef2aca8cb1bdf78434dafcb0" UNIQUE ("id"))`);
        await queryRunner.query(`CREATE TABLE "task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "date_created" datetime NOT NULL, "date_completed" datetime, "note" text, "proposed_time" time, "executor_user_id" integer, "assigned_user_id" integer, "frequency_id" integer, "household_id" integer, "category_id" integer)`);
        await queryRunner.query(`CREATE TABLE "household_member" ("user_id" integer PRIMARY KEY NOT NULL, "date_created" datetime NOT NULL, "is_default" boolean, "is_owner" boolean NOT NULL, "description" varchar(40), "household_id" integer, CONSTRAINT "UQ_66898819f7c858a081a9dcff3fc" UNIQUE ("user_id"), CONSTRAINT "REL_66898819f7c858a081a9dcff3f" UNIQUE ("user_id"))`);
        await queryRunner.query(`CREATE TABLE "household_member_invitation" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "email" varchar(255) NOT NULL, "full_name" varchar(100), "date_created" datetime NOT NULL, "date_accepted" datetime, "sender_user_id" integer, "household_id" integer, CONSTRAINT "UQ_5c20dd2cc000411aa800ddd20ce" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE TABLE "household" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(100) NOT NULL, "main_user_id" integer)`);
        await queryRunner.query(`CREATE TABLE "household_category" ("household_id" integer NOT NULL, "category_id" integer NOT NULL, "custom_name" varchar(60), PRIMARY KEY ("household_id", "category_id"))`);
        await queryRunner.query(`CREATE TABLE "temporary_category_task" ("category_id" integer NOT NULL, "task_id" integer NOT NULL, "relevance" integer, "frequency_id" integer, CONSTRAINT "FK_3c6e43c948df93c81793a50e321" FOREIGN KEY ("frequency_id") REFERENCES "frequency" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_706dd760a331f1f5093a54e47b4" FOREIGN KEY ("task_id") REFERENCES "task_template" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_66b0761bd146f84a6dd8f4a31db" FOREIGN KEY ("category_id") REFERENCES "category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("category_id", "task_id"))`);
        await queryRunner.query(`INSERT INTO "temporary_category_task"("category_id", "task_id", "relevance", "frequency_id") SELECT "category_id", "task_id", "relevance", "frequency_id" FROM "category_task"`);
        await queryRunner.query(`DROP TABLE "category_task"`);
        await queryRunner.query(`ALTER TABLE "temporary_category_task" RENAME TO "category_task"`);
        await queryRunner.query(`CREATE TABLE "temporary_task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "date_created" datetime NOT NULL, "date_completed" datetime, "note" text, "proposed_time" time, "executor_user_id" integer, "assigned_user_id" integer, "frequency_id" integer, "household_id" integer, "category_id" integer, CONSTRAINT "FK_9b2e45879240b2c619b0d2273cf" FOREIGN KEY ("executor_user_id") REFERENCES "household_member" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f3172a11cafc66aa03fded6cf8c" FOREIGN KEY ("assigned_user_id") REFERENCES "household_member" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_b6aa8a02ed2e029ce4f88c7e75a" FOREIGN KEY ("frequency_id") REFERENCES "frequency" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_d79514b8dcb967473f114309117" FOREIGN KEY ("household_id", "category_id") REFERENCES "household_category" ("household_id", "category_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_task"("id", "date_created", "date_completed", "note", "proposed_time", "executor_user_id", "assigned_user_id", "frequency_id", "household_id", "category_id") SELECT "id", "date_created", "date_completed", "note", "proposed_time", "executor_user_id", "assigned_user_id", "frequency_id", "household_id", "category_id" FROM "task"`);
        await queryRunner.query(`DROP TABLE "task"`);
        await queryRunner.query(`ALTER TABLE "temporary_task" RENAME TO "task"`);
        await queryRunner.query(`CREATE TABLE "temporary_household_member" ("user_id" integer PRIMARY KEY NOT NULL, "date_created" datetime NOT NULL, "is_default" boolean, "is_owner" boolean NOT NULL, "description" varchar(40), "household_id" integer, CONSTRAINT "UQ_66898819f7c858a081a9dcff3fc" UNIQUE ("user_id"), CONSTRAINT "REL_66898819f7c858a081a9dcff3f" UNIQUE ("user_id"), CONSTRAINT "FK_66898819f7c858a081a9dcff3fc" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_6c47781879f802c55b436b40d46" FOREIGN KEY ("household_id") REFERENCES "household" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_household_member"("user_id", "date_created", "is_default", "is_owner", "description", "household_id") SELECT "user_id", "date_created", "is_default", "is_owner", "description", "household_id" FROM "household_member"`);
        await queryRunner.query(`DROP TABLE "household_member"`);
        await queryRunner.query(`ALTER TABLE "temporary_household_member" RENAME TO "household_member"`);
        await queryRunner.query(`CREATE TABLE "temporary_household_member_invitation" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "email" varchar(255) NOT NULL, "full_name" varchar(100), "date_created" datetime NOT NULL, "date_accepted" datetime, "sender_user_id" integer, "household_id" integer, CONSTRAINT "UQ_5c20dd2cc000411aa800ddd20ce" UNIQUE ("email"), CONSTRAINT "FK_e8c3c9b395875e846dc7d331ba4" FOREIGN KEY ("sender_user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_2ee1edf2f82767d9a5aec2f4d4e" FOREIGN KEY ("household_id") REFERENCES "household" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_household_member_invitation"("id", "email", "full_name", "date_created", "date_accepted", "sender_user_id", "household_id") SELECT "id", "email", "full_name", "date_created", "date_accepted", "sender_user_id", "household_id" FROM "household_member_invitation"`);
        await queryRunner.query(`DROP TABLE "household_member_invitation"`);
        await queryRunner.query(`ALTER TABLE "temporary_household_member_invitation" RENAME TO "household_member_invitation"`);
        await queryRunner.query(`CREATE TABLE "temporary_household" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(100) NOT NULL, "main_user_id" integer, CONSTRAINT "FK_962e1d1d579613af118620a522b" FOREIGN KEY ("main_user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_household"("id", "name", "main_user_id") SELECT "id", "name", "main_user_id" FROM "household"`);
        await queryRunner.query(`DROP TABLE "household"`);
        await queryRunner.query(`ALTER TABLE "temporary_household" RENAME TO "household"`);
        await queryRunner.query(`CREATE TABLE "temporary_household_category" ("household_id" integer NOT NULL, "category_id" integer NOT NULL, "custom_name" varchar(60), CONSTRAINT "FK_fd3fcd3c32b8e47163f0082c0eb" FOREIGN KEY ("category_id") REFERENCES "category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_783419d4377a1b5d6f49066f71a" FOREIGN KEY ("household_id") REFERENCES "household" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("household_id", "category_id"))`);
        await queryRunner.query(`INSERT INTO "temporary_household_category"("household_id", "category_id", "custom_name") SELECT "household_id", "category_id", "custom_name" FROM "household_category"`);
        await queryRunner.query(`DROP TABLE "household_category"`);
        await queryRunner.query(`ALTER TABLE "temporary_household_category" RENAME TO "household_category"`);
        await queryRunner.query(`DROP INDEX "IDX_4c5f2c23c34f3921fbad2cd394"`);
        await queryRunner.query(`DROP INDEX "IDX_95bf94c61795df25a515435010"`);
        await queryRunner.query(`CREATE TABLE "temporary_user_groups" ("user_id" integer NOT NULL, "group_id" integer NOT NULL, CONSTRAINT "FK_95bf94c61795df25a5154350102" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_4c5f2c23c34f3921fbad2cd3940" FOREIGN KEY ("group_id") REFERENCES "group" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("user_id", "group_id"))`);
        await queryRunner.query(`INSERT INTO "temporary_user_groups"("user_id", "group_id") SELECT "user_id", "group_id" FROM "user_groups"`);
        await queryRunner.query(`DROP TABLE "user_groups"`);
        await queryRunner.query(`ALTER TABLE "temporary_user_groups" RENAME TO "user_groups"`);
        await queryRunner.query(`CREATE INDEX "IDX_4c5f2c23c34f3921fbad2cd394" ON "user_groups" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_95bf94c61795df25a515435010" ON "user_groups" ("user_id") `);
        await queryRunner.query(`DROP INDEX "IDX_7514fdc446a1fdcf5b2d39cda6"`);
        await queryRunner.query(`DROP INDEX "IDX_3924be6485a5b5d0d2fe1a94c0"`);
        await queryRunner.query(`CREATE TABLE "temporary_group_permissions" ("group_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "FK_3924be6485a5b5d0d2fe1a94c08" FOREIGN KEY ("group_id") REFERENCES "group" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_7514fdc446a1fdcf5b2d39cda60" FOREIGN KEY ("permission_id") REFERENCES "permission" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("group_id", "permission_id"))`);
        await queryRunner.query(`INSERT INTO "temporary_group_permissions"("group_id", "permission_id") SELECT "group_id", "permission_id" FROM "group_permissions"`);
        await queryRunner.query(`DROP TABLE "group_permissions"`);
        await queryRunner.query(`ALTER TABLE "temporary_group_permissions" RENAME TO "group_permissions"`);
        await queryRunner.query(`CREATE INDEX "IDX_7514fdc446a1fdcf5b2d39cda6" ON "group_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3924be6485a5b5d0d2fe1a94c0" ON "group_permissions" ("group_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_3924be6485a5b5d0d2fe1a94c0"`);
        await queryRunner.query(`DROP INDEX "IDX_7514fdc446a1fdcf5b2d39cda6"`);
        await queryRunner.query(`ALTER TABLE "group_permissions" RENAME TO "temporary_group_permissions"`);
        await queryRunner.query(`CREATE TABLE "group_permissions" ("group_id" integer NOT NULL, "permission_id" integer NOT NULL, PRIMARY KEY ("group_id", "permission_id"))`);
        await queryRunner.query(`INSERT INTO "group_permissions"("group_id", "permission_id") SELECT "group_id", "permission_id" FROM "temporary_group_permissions"`);
        await queryRunner.query(`DROP TABLE "temporary_group_permissions"`);
        await queryRunner.query(`CREATE INDEX "IDX_3924be6485a5b5d0d2fe1a94c0" ON "group_permissions" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7514fdc446a1fdcf5b2d39cda6" ON "group_permissions" ("permission_id") `);
        await queryRunner.query(`DROP INDEX "IDX_95bf94c61795df25a515435010"`);
        await queryRunner.query(`DROP INDEX "IDX_4c5f2c23c34f3921fbad2cd394"`);
        await queryRunner.query(`ALTER TABLE "user_groups" RENAME TO "temporary_user_groups"`);
        await queryRunner.query(`CREATE TABLE "user_groups" ("user_id" integer NOT NULL, "group_id" integer NOT NULL, PRIMARY KEY ("user_id", "group_id"))`);
        await queryRunner.query(`INSERT INTO "user_groups"("user_id", "group_id") SELECT "user_id", "group_id" FROM "temporary_user_groups"`);
        await queryRunner.query(`DROP TABLE "temporary_user_groups"`);
        await queryRunner.query(`CREATE INDEX "IDX_95bf94c61795df25a515435010" ON "user_groups" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c5f2c23c34f3921fbad2cd394" ON "user_groups" ("group_id") `);
        await queryRunner.query(`ALTER TABLE "household_category" RENAME TO "temporary_household_category"`);
        await queryRunner.query(`CREATE TABLE "household_category" ("household_id" integer NOT NULL, "category_id" integer NOT NULL, "custom_name" varchar(60), PRIMARY KEY ("household_id", "category_id"))`);
        await queryRunner.query(`INSERT INTO "household_category"("household_id", "category_id", "custom_name") SELECT "household_id", "category_id", "custom_name" FROM "temporary_household_category"`);
        await queryRunner.query(`DROP TABLE "temporary_household_category"`);
        await queryRunner.query(`ALTER TABLE "household" RENAME TO "temporary_household"`);
        await queryRunner.query(`CREATE TABLE "household" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(100) NOT NULL, "main_user_id" integer)`);
        await queryRunner.query(`INSERT INTO "household"("id", "name", "main_user_id") SELECT "id", "name", "main_user_id" FROM "temporary_household"`);
        await queryRunner.query(`DROP TABLE "temporary_household"`);
        await queryRunner.query(`ALTER TABLE "household_member_invitation" RENAME TO "temporary_household_member_invitation"`);
        await queryRunner.query(`CREATE TABLE "household_member_invitation" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "email" varchar(255) NOT NULL, "full_name" varchar(100), "date_created" datetime NOT NULL, "date_accepted" datetime, "sender_user_id" integer, "household_id" integer, CONSTRAINT "UQ_5c20dd2cc000411aa800ddd20ce" UNIQUE ("email"))`);
        await queryRunner.query(`INSERT INTO "household_member_invitation"("id", "email", "full_name", "date_created", "date_accepted", "sender_user_id", "household_id") SELECT "id", "email", "full_name", "date_created", "date_accepted", "sender_user_id", "household_id" FROM "temporary_household_member_invitation"`);
        await queryRunner.query(`DROP TABLE "temporary_household_member_invitation"`);
        await queryRunner.query(`ALTER TABLE "household_member" RENAME TO "temporary_household_member"`);
        await queryRunner.query(`CREATE TABLE "household_member" ("user_id" integer PRIMARY KEY NOT NULL, "date_created" datetime NOT NULL, "is_default" boolean, "is_owner" boolean NOT NULL, "description" varchar(40), "household_id" integer, CONSTRAINT "UQ_66898819f7c858a081a9dcff3fc" UNIQUE ("user_id"), CONSTRAINT "REL_66898819f7c858a081a9dcff3f" UNIQUE ("user_id"))`);
        await queryRunner.query(`INSERT INTO "household_member"("user_id", "date_created", "is_default", "is_owner", "description", "household_id") SELECT "user_id", "date_created", "is_default", "is_owner", "description", "household_id" FROM "temporary_household_member"`);
        await queryRunner.query(`DROP TABLE "temporary_household_member"`);
        await queryRunner.query(`ALTER TABLE "task" RENAME TO "temporary_task"`);
        await queryRunner.query(`CREATE TABLE "task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "date_created" datetime NOT NULL, "date_completed" datetime, "note" text, "proposed_time" time, "executor_user_id" integer, "assigned_user_id" integer, "frequency_id" integer, "household_id" integer, "category_id" integer)`);
        await queryRunner.query(`INSERT INTO "task"("id", "date_created", "date_completed", "note", "proposed_time", "executor_user_id", "assigned_user_id", "frequency_id", "household_id", "category_id") SELECT "id", "date_created", "date_completed", "note", "proposed_time", "executor_user_id", "assigned_user_id", "frequency_id", "household_id", "category_id" FROM "temporary_task"`);
        await queryRunner.query(`DROP TABLE "temporary_task"`);
        await queryRunner.query(`ALTER TABLE "category_task" RENAME TO "temporary_category_task"`);
        await queryRunner.query(`CREATE TABLE "category_task" ("category_id" integer NOT NULL, "task_id" integer NOT NULL, "relevance" integer, "frequency_id" integer, PRIMARY KEY ("category_id", "task_id"))`);
        await queryRunner.query(`INSERT INTO "category_task"("category_id", "task_id", "relevance", "frequency_id") SELECT "category_id", "task_id", "relevance", "frequency_id" FROM "temporary_category_task"`);
        await queryRunner.query(`DROP TABLE "temporary_category_task"`);
        await queryRunner.query(`DROP TABLE "household_category"`);
        await queryRunner.query(`DROP TABLE "household"`);
        await queryRunner.query(`DROP TABLE "household_member_invitation"`);
        await queryRunner.query(`DROP TABLE "household_member"`);
        await queryRunner.query(`DROP TABLE "task"`);
        await queryRunner.query(`DROP TABLE "frequency"`);
        await queryRunner.query(`DROP TABLE "category_task"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "task_template"`);
        await queryRunner.query(`DROP INDEX "IDX_3924be6485a5b5d0d2fe1a94c0"`);
        await queryRunner.query(`DROP INDEX "IDX_7514fdc446a1fdcf5b2d39cda6"`);
        await queryRunner.query(`ALTER TABLE "group_permissions" RENAME TO "temporary_group_permissions"`);
        await queryRunner.query(`CREATE TABLE "group_permissions" ("group_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "FK_7514fdc446a1fdcf5b2d39cda60" FOREIGN KEY ("permission_id") REFERENCES "permission" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_3924be6485a5b5d0d2fe1a94c08" FOREIGN KEY ("group_id") REFERENCES "group" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("group_id", "permission_id"))`);
        await queryRunner.query(`INSERT INTO "group_permissions"("group_id", "permission_id") SELECT "group_id", "permission_id" FROM "temporary_group_permissions"`);
        await queryRunner.query(`DROP TABLE "temporary_group_permissions"`);
        await queryRunner.query(`CREATE INDEX "IDX_3924be6485a5b5d0d2fe1a94c0" ON "group_permissions" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7514fdc446a1fdcf5b2d39cda6" ON "group_permissions" ("permission_id") `);
        await queryRunner.query(`DROP INDEX "IDX_95bf94c61795df25a515435010"`);
        await queryRunner.query(`DROP INDEX "IDX_4c5f2c23c34f3921fbad2cd394"`);
        await queryRunner.query(`ALTER TABLE "user_groups" RENAME TO "temporary_user_groups"`);
        await queryRunner.query(`CREATE TABLE "user_groups" ("user_id" integer NOT NULL, "group_id" integer NOT NULL, CONSTRAINT "FK_4c5f2c23c34f3921fbad2cd3940" FOREIGN KEY ("group_id") REFERENCES "group" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_95bf94c61795df25a5154350102" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("user_id", "group_id"))`);
        await queryRunner.query(`INSERT INTO "user_groups"("user_id", "group_id") SELECT "user_id", "group_id" FROM "temporary_user_groups"`);
        await queryRunner.query(`DROP TABLE "temporary_user_groups"`);
        await queryRunner.query(`CREATE INDEX "IDX_95bf94c61795df25a515435010" ON "user_groups" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c5f2c23c34f3921fbad2cd394" ON "user_groups" ("group_id") `);
    }

}
