export enum PageKey {
	Home = 'home',
	Dashboard = 'dashboard',
	SignIn = 'sign-in',
	SignUp = 'signup',
	UserSettings = 'user-settings',
	ForgotPassword = 'forgot-password',
	ResetPassword = 'reset-password',
	ChangePassword = 'change-password',
	UserProfile = 'user-profile',
	VerifyEmail = 'verify-account-email',
	VerifyPhone = 'verify-account-phone',
	Admin = 'admin',
	Household = 'household',
	PageNotFound = 'not-found',
	Error404 = 'error-404',
	Error500 = 'error-500',

	Todo = 'todo',
}
