export enum Resources {
	User = 'user',
	Role = 'user-group',
	Permission = 'permission',
	Todo = 'todo',
	Household = 'household',
	HouseholdRoom = 'household-room',
	Task = 'task',
	TaskTemplate = 'task-template',
	RoomType = 'room-type',
	Frequency = 'frequency',
	Operation = 'operation',
	Admin = 'admin',
	Room = 'room',
}
