export enum RoomTypes {
	LivingRoom = 1,
	Bedroom = 2,
	Kitchen = 3,
	DiningRoom = 4,
	FamilyRoom = 5,
	GuestRoom = 6,
	Bathroom = 7,
	GameRoom = 8,
	Basement = 9,
	HomeOffice = 10,
	Hallway = 11,
	Nursery = 12,
	Playroom = 13,
	StorageRoom = 14,
	Garage = 15,
	LaundryRoom = 16,
	Patio = 17,
	Stairs = 18,
}
